import { cn } from "@/lib/utils";
import "./globals.css";

import { SearchHeader } from "@/components/SearchHeader";
import { ExternalLink } from "@/components/external-link";
import { TooltipProvider } from "@/components/ui/tooltip";
import type { Metadata } from "next";
import { ThemeProvider } from "next-themes";
import { Fraunces, Source_Serif_4 } from "next/font/google";

const fontHeading = Fraunces({
	variable: "--font-heading",
	weight: "600",
	subsets: ["latin"],
	display: "swap",
});

const fontBody = Source_Serif_4({
	variable: "--font-body",
	weight: "400",
	subsets: ["latin"],
	display: "swap",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" suppressHydrationWarning>
			<head />
			<body
				className={cn(
					fontHeading.variable,
					fontBody.variable,
					"supports-[height:100cqh]:min-h-[100cqh] supports-[height:100svh]:min-h-[100svh]",
					"flex flex-col gap-4",
				)}
			>
				<ThemeProvider
					attribute="class"
					defaultTheme="system"
					enableSystem
					disableTransitionOnChange
				>
					<TooltipProvider>
						<main className="flex-1 w-full max-w-screen-md mx-auto flex flex-col py-2 px-4 gap-2">
							<SearchHeader />
							{children}
						</main>
						<footer className="flex flex-row justify-end items-center p-4 border-t">
							<div className="flex flex-col gap-1 text-xs items-end">
								<span className="text-muted-foreground">
									Content courtesy of{" "}
									<ExternalLink href="https://claude.ai/">Claude 3.5 Sonnet</ExternalLink>
								</span>
								<span className="text-muted-foreground hidden md:block">
									Map via <ExternalLink href="https://protomaps.com">Protomaps</ExternalLink> &{" "}
									<ExternalLink href="https://maplibre.org">maplibre</ExternalLink>, map data via{" "}
									<ExternalLink href="https://docs.mapbox.com/api/search/search-box/">
										Mapbox
									</ExternalLink>{" "}
									& <ExternalLink href="https://whosonfirst.org/">Who's On First</ExternalLink>
								</span>
							</div>
						</footer>
					</TooltipProvider>
				</ThemeProvider>
			</body>
		</html>
	);
}
