import { cn } from "@/lib/utils";
import "./globals.css";

import { SearchHeader } from "@/components/SearchHeader";
import type { Metadata } from "next";
import { ThemeProvider } from "next-themes";
import { Fraunces, Source_Serif_4 } from "next/font/google";

const fontHeading = Fraunces({
	variable: "--font-heading",
	weight: "600",
	subsets: ["latin"],
	display: "swap",
});

const fontBody = Source_Serif_4({
	variable: "--font-body",
	weight: "400",
	subsets: ["latin"],
	display: "swap",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" suppressHydrationWarning>
			<head />
			<body className={cn(fontHeading.variable, fontBody.variable)}>
				<ThemeProvider
					attribute="class"
					defaultTheme="system"
					enableSystem
					disableTransitionOnChange
				>
					<main className="max-w-screen-md mx-auto flex flex-col py-2 px-4 gap-2">
						<SearchHeader />
						{children}
					</main>
				</ThemeProvider>
			</body>
		</html>
	);
}
